### PR TITLE
Reposition Ok & Cancel button and set Accept and CancelButton in Goto…

### PR DESCRIPTION
**Pull request by 123marvin123**
…, InputBox and NewForm

### CODE REVIEW

**Comment by WopsS** [comment]
Hello,
Thank you for the pull request but I think it is better to be OK/Cancel not Cancel/OK.

**Comment by 123marvin123** [comment]
Ok, but I think you should still use the Form's Accept/CancelButton, because it enables a native Windows feeling. Many apps use this mechanism, because it allows a faster workflow and you don't have to touch your mouse after you've typed something in.

**Comment by WopsS** [comment]
You are right, but in windows forms the positions are Yes / No / Cancel.

**Comment by WopsS** [comment]
Oh, I had some forms with Cancel button on the left and OK button on the right, maybe this is why you changed positions for **GoToLine** form. Anyway I changed them back.

Thank you :)

**Pull request merged**
